---
name: Daniel
surname: Alhassan
position: "PhD Candidate"
address: "Department of Mathematics and Statistics \n Missouri University of Science and Technology"
profilepic: "images/img1.jpg"
headcolor: 00008B
docname: CV
phone: +1 504 931 7691
www: "dalhassan.netlify.app"
email: "danhmed@gmail.com"
github: DanielAlhassan
orcid: 0000-0003-0944-5818
#googlescholar:  
linkedin: daniel-alhassan-41981331
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::awesomecv:
    page_total: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
require(xfun)
packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data structure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative File Paths
             ,'readr'     # Data Loading
             ,'glue'      # String Manipulation
            )
xfun::pkg_attach2(packages, message = FALSE)
source(file = here("r","data.r"))
```

# Research Interests

```{r PROJECTS}
research.interests %>%
  detailed_entries(
    with = area,
    what = subarea
  )
```

# Work Experience

```{r EMPLOYMENT}
work %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} --- {endMonth} {endYear}",.na = ""),
    where = where
  )
```

# Education

```{r EDUCATION}
edu %>%
  detailed_entries(
    with = inst,
    what = degree,
    why = detail,
    when = glue::glue("{startYear} --- {endYear}",.na = ""),
    where = where
  )
```

# Publications

```{r PUBLICATIONS}
 bibliography_entries("packages.bib") 

manuinprep %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )
```


# Conferences Attended
```{r}
 conference %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )
```

# Talks and Workshops 
```{r}
talks %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )
```

# Skills

```{r SKILLS}
skills %>%
  detailed_entries(
    with = area,
    what = skills
  )
```

# Awards and Honors

```{r HONORS}
honors %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )
```

<!-- \pagebreak -->

# Certifications

```{r CERTIFICATIONS}
certifications %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )
```

